# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_TOUCHSCREEN_GOODIX_BRL)            += goodix_core.o
goodix_core-y := \
			goodix_brl_spi.o \
			goodix_ts_core.o \
			goodix_brl_hw.o \
			goodix_cfg_bin.o \
			goodix_ts_utils.o \
			goodix_brl_fwupdate.o \
			goodix_ts_test.o

obj-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_TOOLS)       += goodix_ts_tools.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_BRL_GESTURE)     += goodix_ts_gesture.o
