/* SPDX-License-Identifier: GPL-2.0-only */

#define CONFIG_TOUCHSCREEN_XIAOMI_TOUCHFEATURE 1
#define CONFIG_TOUCHSCREEN_FOCALTECH 1
#define CONFIG_TOUCHSCREEN_GOODIX_BRL 1
#define CONFIG_TOUCHSCREEN_GOODIX_BRL_SPI 1
